INSERT INTO skills (code, name, category, is_active, sort_order)
VALUES
    ('JAVA',            'Java',                'BACKEND',  TRUE, 10),
    ('SPRING',          'Spring',              'BACKEND',  TRUE, 20),
    ('KOTLIN',          'Kotlin',              'BACKEND',  TRUE, 30),
    ('GO',              'Go',                  'BACKEND',  TRUE, 40),
    ('PYTHON',          'Python',              'BACKEND',  TRUE, 50),
    ('NODEJS',          'Node.js',             'BACKEND',  TRUE, 60),
    ('POSTGRESQL',      'PostgreSQL',          'BACKEND',  TRUE, 70),
    ('MYSQL',           'MySQL',               'BACKEND',  TRUE, 80),
    ('MONGODB',         'MongoDB',             'BACKEND',  TRUE, 90),
    ('REDIS',           'Redis',               'BACKEND',  TRUE, 100),
    ('KAFKA',           'Kafka',               'BACKEND',  TRUE, 110),
    ('RABBITMQ',        'RabbitMQ',            'BACKEND',  TRUE, 120),
    ('REST',            'REST',                'BACKEND',  TRUE, 130),
    ('GRAPHQL',         'GraphQL',             'BACKEND',  TRUE, 140),
    ('GRPC',            'gRPC',                'BACKEND',  TRUE, 150),

    ('REACT',           'React',               'FRONTEND', TRUE, 200),
    ('VUE',             'Vue',                 'FRONTEND', TRUE, 210),
    ('ANGULAR',         'Angular',             'FRONTEND', TRUE, 220),
    ('TYPESCRIPT',      'TypeScript',          'FRONTEND', TRUE, 230),
    ('JAVASCRIPT',      'JavaScript',          'FRONTEND', TRUE, 240),
    ('HTML',            'HTML',                'FRONTEND', TRUE, 250),
    ('CSS',             'CSS',                 'FRONTEND', TRUE, 260),
    ('SASS',            'Sass',                'FRONTEND', TRUE, 270),
    ('WEBPACK',         'Webpack',             'FRONTEND', TRUE, 280),
    ('VITE',            'Vite',                'FRONTEND', TRUE, 290),

    ('KOTLIN_ANDROID',  'Kotlin (Android)',    'MOBILE',   TRUE, 300),
    ('SWIFT',           'Swift',               'MOBILE',   TRUE, 310),
    ('FLUTTER',         'Flutter',             'MOBILE',   TRUE, 320),
    ('REACT_NATIVE',    'React Native',        'MOBILE',   TRUE, 330),

    ('DOCKER',          'Docker',              'DEVOPS',   TRUE, 400),
    ('KUBERNETES',      'Kubernetes',          'DEVOPS',   TRUE, 410),
    ('JENKINS',         'Jenkins',             'DEVOPS',   TRUE, 420),
    ('GITLAB_CI',       'GitLab CI',           'DEVOPS',   TRUE, 430),
    ('GITHUB_ACTIONS',  'GitHub Actions',      'DEVOPS',   TRUE, 440),
    ('TERRAFORM',       'Terraform',           'DEVOPS',   TRUE, 450),
    ('ANSIBLE',         'Ansible',             'DEVOPS',   TRUE, 460),
    ('LINUX',           'Linux',               'DEVOPS',   TRUE, 470),
    ('NGINX',           'Nginx',               'DEVOPS',   TRUE, 480),

    ('SQL',             'SQL',                 'DATA',     TRUE, 500),
    ('PYTORCH',         'PyTorch',             'DATA',     TRUE, 510),
    ('TENSORFLOW',      'TensorFlow',          'DATA',     TRUE, 520),
    ('PANDAS',          'Pandas',              'DATA',     TRUE, 530),
    ('NUMPY',           'NumPy',               'DATA',     TRUE, 540),
    ('SPARK',           'Apache Spark',        'DATA',     TRUE, 550),
    ('HADOOP',          'Hadoop',              'DATA',     TRUE, 560),
    ('AIRFLOW',         'Airflow',             'DATA',     TRUE, 570),

    ('SELENIUM',        'Selenium',            'QA',       TRUE, 600),
    ('JUNIT',           'JUnit',               'QA',       TRUE, 610),
    ('TESTNG',          'TestNG',              'QA',       TRUE, 620),
    ('PYTEST',          'pytest',              'QA',       TRUE, 630),
    ('POSTMAN',         'Postman',             'QA',       TRUE, 640),
    ('JMETER',          'JMeter',              'QA',       TRUE, 650),
    ('ALLURE',          'Allure',              'QA',       TRUE, 660),

    ('GIT',             'Git',                 'TOOLING',  TRUE, 700),
    ('JIRA',            'Jira',                'TOOLING',  TRUE, 710),
    ('CONFLUENCE',      'Confluence',          'TOOLING',  TRUE, 720),
    ('MAVEN',           'Maven',               'TOOLING',  TRUE, 730),
    ('GRADLE',          'Gradle',              'TOOLING',  TRUE, 740)
    ON CONFLICT (code) DO NOTHING;